version: "3.9"  # optional since v1.27.0
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-cache
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_PORT=5432
  postgres:
    image: postgres:14
    volumes:
    - postgresvol:/var/lib/postgresql/data/
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DB=postgres
volumes:
  postgresvol: {}